### ISSUE TITLE
Not Loading - KeyError: 'USERPROFILE'

### ISSUE THREAD

**Issue by GTXAuro** [xanthe1337/Discordapp-TokenGrabber#1]
Hi Dev,
Good work! Somehow I can't get it to work though. Installed all dependencies and compiled.
Running **Kali Linux 2020** with **Python 3.7**

--------------------------
**Error is as follows:**
auro@kali:~/Desktop/Discordapp-TokenGrabber-master$ python3 main.py 
Traceback (most recent call last):
  File "main.py", line 3, in <module>
    class Data():
  File "main.py", line 4, in Data
    computerName = os.environ['USERPROFILE']
  File "/usr/lib/python3.7/os.py", line 681, in __getitem__
    raise KeyError(key) from None
KeyError: 'USERPROFILE'

![Screenshot_1](https://user-images.githubusercontent.com/23747705/77851238-35efbd00-71d8-11ea-8f03-a1bf1a97b26b.png)

Your help would be very much appreciated.
Regards

**Comment by xanthe1337** [comment]
That line is unused, you can remove it and should work like charm

**Comment by GTXAuro** [comment]
Removed, now I get error

auro@kali:~/Desktop/Discordapp-TokenGrabber-master$ python3 main.py 
Traceback (most recent call last):
  File "main.py", line 3, in <module>
    class Data():
  File "main.py", line 7, in Data
    appData + "\\Discord\\Local Storage\\leveldb", 
TypeError: unsupported operand type(s) for +: 'NoneType' and 'str'
----------------------------
Am I doing something wrong here? Or perhaps its some Python incompatibility?

![Screenshot_1](https://user-images.githubusercontent.com/23747705/77852235-cc72ad00-71dd-11ea-9dd0-a88ba4e020f6.png)

**Comment by xanthe1337** [comment]
Seems like youre running in some OS/platform that isnt supported, ill look in that and fix it, thanks

**Comment by GTXAuro** [comment]
Thanks. Here's some diagnostic information to make life a bit easier.

OS: Kali Rolling 2020.1
Kernel: Linux 5.4.0-kali4-amd64
Python: Python 3.7.7

**Comment by xanthe1337** [comment]
Thank you a lot, ill fix this issue.

**Comment by NiNj4HAXYT** [comment]
Accept my Friend request 「ᑎ I ᑎ ᒍ ᗩ ╮ᴼᴾ」👑#7777
