### ISSUE TITLE
What are the legalities of this?

### ISSUE THREAD

**Issue by Bevan0** [xanthe1337/Discordapp-TokenGrabber#4]
Just wondering.

**Comment by xanthe1337** [comment]
why does that bother u

**Comment by Bevan0** [comment]
Did you even read my first message?

**Comment by xanthe1337** [comment]
because i do other stuff, i dont surf github 24/7 anyways

**Comment by Jinxzyy** [comment]
its your choice to whether or not you run things on your pc, is you lose your discord account from running something thats your own problem xD

**Comment by Bevan0** [comment]
So basically I'm allowed to use this to steal someone else's Discord acc with 0 consequences?
That's basically what both of you just said, you know.

**Comment by xanthe1337** [comment]
i dont see why there would be any consequences, use vpn if you're insecure and thats all.
